import "dotenv/config";
import { supabase } from "../src/services/supabase/client.js";
const { data } = await supabase.from("article_jobs").select("metadata, updated_at").eq("id","5c9a77d1-ca3b-4315-89d5-8dd8511717d2").single();
const m = data!.metadata as any;
console.log("updated_at:", data!.updated_at);
console.log("imageRequirements:", JSON.stringify(m.imageRequirements));
console.log("imageDirectUrls:", JSON.stringify(m.imageDirectUrls));
console.log("imageEditRequestMessageId:", m.imageEditRequestMessageId);
console.log("webImagesReadyAt:", m.webImagesReadyAt);
console.log("channelManuscriptsReadyAt:", m.channelManuscriptsReadyAt);
for (const i of (m.images ?? [])) console.log(`[${i.index}] ${i.url ? "채움" : "빔"} ${i.provider ?? ""}`);
